[workspace]
members = ["projects/*"]
default-members = [
    "projects/mosaic-craft-core",
    "projects/mosaic-craft-web",
]
exclude = [
    "projects/.DS_Store",
    "projects/mosaic-craft-themes",
]

[profile.release]
lto = true
