[workspace]
members = ["projects/*"]
default-members = [
    "projects/lego-art-core",
    "projects/lego-art-web",
    "projects/lego-art-themes",
]
exclude = [
    "projects/.DS_Store",
    "projects/ascii-art-wolfram",
]

[profile.release]
lto = true
